### PR TITLE
Add support for faccessat2

### PR DESCRIPTION
**Pull request by r1olo**

### CODE REVIEW

**Comment by michalbednarski** [comment]
Overall looks nice, although it seems `faccessat2` won't be available on Android as it is [not on list of syscalls allowed by Androids seccomp policy](https://android.googlesource.com/platform/bionic/+/refs/tags/android-11.0.0_r42/libc/SYSCALLS.TXT) and [probably won't be](https://android.googlesource.com/platform/bionic/+/79dbdc3c22d924540c86ed4ea5a7a6945392760b/libc/bionic/faccessat.cpp#46)

What was this tested with and what program needs `faccessat2` to function?
Was this on Android? (or this change is just for running proot on normal Linux)?
If `faccessat2` is required for program operation then on Android it would be necessary to add [SIGSYS handler](https://github.com/termux/proot/blob/master/src/tracee/seccomp.c) for it.

**Comment by r1olo** [comment]
Ah yes, my bad, I should have provided more info. This is to make proot work on normal Linux systems that implement the new `faccessat2`.  I sent the pull request here and not to the [original proot repo](https://github.com/proot-me/proot) because Termux's fork doesn't crash and also supports `statx` system call (without that `ls` and other commands just don't work).

**Comment by michalbednarski** [comment]
Ok, thanks, merged.

Out of curiosity, is `faccessat2` needed for any particular program?

**Comment by r1olo** [comment]
Yes, for example `bash` uses it to test whether a file is readable or writable (`[[ -r $file]]` and `[[ -w $file ]]`), so any script that relied on that was broken. `pacman` also uses it to check whether its database exists in the system.

**Comment by michalbednarski** [comment]
So I've re-checked and it looks like [`faccessat2` usage was introduced in glibc-2.33](https://github.com/bminor/glibc/commit/3d3ab573a5f3071992cbc4f57d50d1d29d55bde2), with fallback to `faccessat`+`fstatat64`. That version wasn't yet released for Arch Linux ARM (aarch64), while Arch Linux (x86_64) ships glibc with fallback enabled (no `__ASSUME_FACCESSAT2`), so for Android current default proot fallback implementation `return -ENOSYS;` should be sufficient.

Anyway, thanks again, I didn't know about `faccessat2` before

**Pull request merged**
